implementacao do menu da calculadora
Renato-Queiroz/calculadora pull request #4
Opened 2021-01-20 20:51 UTC by Renato-Queiroz

Implementado menu conforme solicitado, favor analisar o codigo.

2021-01-20 23:46 UTC, CharlesQueiroz requested changes

2021-01-20 23:46 UTC, CharlesQueiroz commented on src/main/java/Calculadora.java
> +            if (opcao.charAt(0) == 'A') {
Trocar if/else por switch.

2021-01-20 23:46 UTC, CharlesQueiroz commented on src/main/java/Calculadora.java
> +        String opcao = scanner.next();
Trocar o tipo de String para Char já que só vai ser digitado uma letra.

2021-01-20 23:46 UTC, CharlesQueiroz commented on src/main/java/Calculadora.java
> +                ProcessBuilder processBuilder = new ProcessBuilder();
remover essa linha

2021-01-20 23:46 UTC, CharlesQueiroz commented on src/main/java/Calculadora.java
> +                ProcessBuilder processBuilder = new ProcessBuilder();
remover essa linha

2021-01-20 23:46 UTC, CharlesQueiroz commented on src/main/java/Calculadora.java
> +                ProcessBuilder processBuilder = new ProcessBuilder();
remover essa linha

2021-01-20 23:46 UTC, CharlesQueiroz commented on src/main/java/Calculadora.java
> +                ProcessBuilder processBuilder = new ProcessBuilder();
remover essa linha

2021-01-20 23:46 UTC, CharlesQueiroz commented on src/main/java/Calculadora.java
> +                ProcessBuilder processBuilder = new ProcessBuilder();
remover essa linha

2021-01-20 23:46 UTC, CharlesQueiroz commented on src/main/java/Calculadora.java
> +                ProcessBuilder processBuilder = new ProcessBuilder();
remover essa linha

2021-01-20 23:46 UTC, CharlesQueiroz commented on src/main/java/Calculadora.java
> +                ProcessBuilder processBuilder = new ProcessBuilder();
remover essa linha

2021-01-20 23:46 UTC, CharlesQueiroz commented on src/main/java/Calculadora.java
> +                ProcessBuilder processBuilder = new ProcessBuilder();
remover essa linha

2021-01-22 04:52 UTC, CharlesQueiroz requested changes

2021-01-22 04:52 UTC, CharlesQueiroz commented on src/main/java/Calculadora.java
> +            switch (opcao.charAt(0)) {
tu já tem a opção salva na variável opcao, entao nao precisa chamar mais o charAt(0). Tu tá chamando esse método 2 vezes. Chama só 1, guarda na variável opcao e usa ela onde precisar.

2021-01-22 04:52 UTC, CharlesQueiroz commented on src/main/java/Calculadora.java
> +        String opcao = scanner.next();
mover a chamada do método toUpperCase() para depois do next() que dai tu já lê em maiúsculo e deixa a linha de baixo pra ser o resultado da chamada do método charAt(0).

2021-01-22 04:52 UTC, CharlesQueiroz commented on src/main/java/Calculadora.java
> +        while (opcao.charAt(0) != 'X') {
trocar por do / wille para evitar de repetir o código: 

opcao = scanner.next();
opcao = opcao.toUpperCase();

na opção default do switch.

2021-01-22 04:52 UTC, CharlesQueiroz commented on src/main/java/Calculadora.java
> +                    opcao = opcao.toUpperCase();
remover essas duas linhas quando trocar para do/wile por nao haver a necessidade delas existirem.

2021-01-22 06:47 UTC, Renato-Queiroz commented on src/main/java/Calculadora.java
> +                ProcessBuilder processBuilder = new ProcessBuilder();
feito.

2021-01-22 06:48 UTC, Renato-Queiroz commented on src/main/java/Calculadora.java
> +                    opcao = opcao.toUpperCase();
feito.

2021-01-22 06:49 UTC, Renato-Queiroz commented on src/main/java/Calculadora.java
> +        while (opcao.charAt(0) != 'X') {
feito.

2021-01-22 06:49 UTC, Renato-Queiroz commented on src/main/java/Calculadora.java
> +        String opcao = scanner.next();
feito.

2021-01-22 06:49 UTC, Renato-Queiroz commented on src/main/java/Calculadora.java
> +            switch (opcao.charAt(0)) {
feito.

2021-01-22 06:50 UTC, Renato-Queiroz commented on src/main/java/Calculadora.java
> +                ProcessBuilder processBuilder = new ProcessBuilder();
feito.

2021-01-22 06:50 UTC, Renato-Queiroz commented on src/main/java/Calculadora.java
> +                ProcessBuilder processBuilder = new ProcessBuilder();
feito.

2021-01-22 06:50 UTC, Renato-Queiroz commented on src/main/java/Calculadora.java
> +                ProcessBuilder processBuilder = new ProcessBuilder();
feito.

2021-01-22 06:51 UTC, Renato-Queiroz commented on src/main/java/Calculadora.java
> +                ProcessBuilder processBuilder = new ProcessBuilder();
feito.

2021-01-22 06:51 UTC, Renato-Queiroz commented on src/main/java/Calculadora.java
> +                ProcessBuilder processBuilder = new ProcessBuilder();
feito.

2021-01-22 06:51 UTC, Renato-Queiroz commented on src/main/java/Calculadora.java
> +                ProcessBuilder processBuilder = new ProcessBuilder();
feito.

2021-01-25 01:25 UTC, closed without merging